### ISSUE TITLE
Updating pypi version

### ISSUE THREAD

**Issue by alexandre** [maximkulkin/hypothesis-regex#9]
Hello,

I tried to use the pypi version, but it's missing the last commit that fixes an import error. Could you update it?
Thanks for the excellent work!

```shell
 ~> mkproject3 hypothesis-regex
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
...
 ~> pip install hypothesis-regex
Collecting hypothesis-regex
  Using cached hypothesis_regex-0.2-py2.py3-none-any.whl
Collecting six>=1.10 (from hypothesis-regex)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting hypothesis>=3.8 (from hypothesis-regex)
Collecting attrs>=16.0.0 (from hypothesis>=3.8->hypothesis-regex)
  Using cached attrs-17.4.0-py2.py3-none-any.whl
Collecting coverage (from hypothesis>=3.8->hypothesis-regex)
  Using cached coverage-4.5.1-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: six, attrs, coverage, hypothesis, hypothesis-regex
Successfully installed attrs-17.4.0 coverage-4.5.1 hypothesis-3.49.0 hypothesis-regex-0.2 six-1.11.0
(hypothesis-regex) alexandre@alexandre-st ~/Development/python/hypothesis-regex 
 ~> python
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hypothesis_regex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alexandre/Envs/hypothesis-regex/lib/python3.6/site-packages/hypothesis_regex.py", line 10, in <module>
    from hypothesis.searchstrategy.reprwrapper import ReprWrapperStrategy
ModuleNotFoundError: No module named 'hypothesis.searchstrategy.reprwrapper'
>>> 
```

Using `pip install -e git+https://github.com/https://github.com/maximkulkin/hypothesis-regex#egg=hypothesis_regex` works.

**Comment by maximkulkin** [comment]
Done
